# Use an official Node.js runtime as a base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code to the container
COPY . .

# Build the React app for production
RUN npm run build

# Expose the port that the app runs on
EXPOSE  5173

# Start the application
CMD ["npm", "start"]
